# Site settings
title: The Big Fat Cat
SEOTitle: 肥猫零零七的博客 | The Big Fat Cat
header-img: img/home-bg.jpg
email: davidxiaozhi@126.com@gmail.com
description: "关于前端与设计、黑客与画家 | 肥猫零零七，Web & Mobile Lover，Front-End Engineer，UX Designer | 这里是 @Hux肥猫零零七 的个人博客，与你一起发现更大的世界。"
keyword: "肥猫零零七, Hux肥猫零零七, Hux, 鬼栈, davidxiaozhi@126.com, @davidxiaozhi@126.com, 肥猫零零七的博客, Hux Blog, 博客, 个人网站, 互联网, 前端, 设计, 产品, 肖玉, Lynn, 肖玉的男朋友"
url: "http://davidxiaozhi.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
gems: [jekyll-paginate]


# SNS settings
RSS: false
weibo_username:     davidxiaozhi@126.com
zhihu_username:     davidxiaozhi@126.com
github_username:    davidxiaozhi@126.com
#twitter_username:  davidxiaozhi@126.com
facebook_username:  davidxiaozhi@126.com



# Build settings
#highlighter: pygments 3.0 is rouge
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter: rouge



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: davidxiaozhi
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: davidxiaozhi.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，做做设计，快乐乐乐的工作，高高兴兴的玩，做一名极客的同时，也不要放弃每一次吃喝玩乐的机会。"
sidebar-avatar: /img/fat_cat.gif      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "Luke的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "解旻的博客",
        href: "http://xieminis.me/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    }
]
